# This is a basic workflow to help you get started with Actions

name: innosetup

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ innosetup ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Chocolatey install innosetup
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-chocolatey@d025252287b66c3fb7d795cc8932dec97630cd53
        uses: crazy-max/ghaction-chocolatey@v1.5.0
        with:
          # Arguments to pass to Chocolatey
          args: install innosetup --install-arguments="'/DIR=innosetup'" --force
          # Docker image to use
      - name: ad
        run: dir
      - name: dir innosetup
        run: dir innosetup
      - name: Run innosetup
        run: innosetup/ICSS.exe test1_script.iss
