# Deploy workflow
# Builds the application for windows and ubuntu and creates distributable. Then creates a new
#   Github release with the tag name and uploads the distributables to the release.
#   Runs only on "v*" tags like "v1.0.0".
name: deploy

on:
  push:
    tags: 
      - v*.*.*
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: check
        run: |
        echo ${GITHUB_REF/refs\/tags\//}
        echo "$(GITHUB_REF#refs/*/)"