# Deploy workflow
# Builds the application for windows and ubuntu and creates distributable. Then creates a new
#   Github release with the tag name and uploads the distributables to the release.
#   Runs only on "v*" tags like "v1.0.0".
name: test

on:
  push:
    tags: 
      - v*.*.*
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: tagname
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: echo 
        run: echo ${{ env.GIT_TAG_NAME }}